services:
  db:
    image: postgres
    container_name: interview-db
    ports:
      - "5434:5432"
    env_file:
      - docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
